### ISSUE TITLE
"Clear All" button

### ISSUE THREAD

**Issue by LyubomirT** [LyubomirT/forcevar#2]
The only way to clear data (all data) from the extension at the moment is to update it in the Extension management panel (or to delete it entirely). This can be simplified by making a "Clear All" button (which also asks for a confirmation) that wipes all data from the extension and makes it look like a fresh start.

**Comment by GiorgosDrivas** [comment]
Hello! I would like to work on this issue.

**Comment by LyubomirT** [comment]
Sure thing! I'll assign the issue to you, thank you for considering to contribute to this project!

**Comment by LyubomirT** [comment]
Implemented
